// types.js
const ABOUT_INCREMENT_COUNT = 'ABOUT_INCREMENT_COUNT';
const ABOUT_DECREMENT_COUNT = 'ABOUT_DECREMENT_COUNT';

const REQUEST_SUBREDDIT_JSON = 'REQUEST_SUBREDDIT_JSON';
const RECEIVE_SUBREDDIT_JSON = 'RECEIVE_SUBREDDIT_JSON';

export default {
    ABOUT_INCREMENT_COUNT,
    ABOUT_DECREMENT_COUNT,
    REQUEST_SUBREDDIT_JSON,
    RECEIVE_SUBREDDIT_JSON
}
