// types.js
const INCREMENT_COUNT = 'INCREMENT_COUNT';
const DECREMENT_COUNT = 'DECREMENT_COUNT';

const REQUEST_SUBREDDIT_JSON = 'REQUEST_SUBREDDIT_JSON';
const RECEIVE_SUBREDDIT_JSON = 'RECEIVE_SUBREDDIT_JSON';

const GET_HOME_SHELTERS = 'GET_HOME_SHELTERS';

export default {
    GET_HOME_SHELTERS,
    INCREMENT_COUNT,
    DECREMENT_COUNT,
    REQUEST_SUBREDDIT_JSON,
    RECEIVE_SUBREDDIT_JSON
}
